apiVersion: apps/v1
kind: Deployment

metadata:
  name: correlation-api
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: correlation-api

  template:
    metadata:
      labels:
        app: correlation-api

    spec:

      imagePullSecrets:
      - name: acr-secret


      containers:
      - name: correlation-api
        image: "{{ .Values.correlation.image.repository }}:{{ .Values.correlation.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}


---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: submission-api
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: submission-api

  template:
    metadata:
      labels:
        app: submission-api

    spec:

      imagePullSecrets:
      - name: acr-secret


      containers:
      - name: submission-api
        image: "{{ .Values.submission.image.repository }}:{{ .Values.submission.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
