apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: deployment-bot-binding
  namespace: orsted-lab

subjects:
- kind: ServiceAccount
  name: deployment-bot
  namespace: orsted-lab

roleRef:
  kind: Role
  name: orsted-lab-reader
  apiGroup: rbac.authorization.k8s.io
