name: Build and Push Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "8b322099-2467-4a7f-a427-003c3dabed69",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }

    - name: Login to ACR
      run: |
        az acr login --name orstedlabacr

    - name: Build and Push correlation-api
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build \
        -t orstedlabacr.azurecr.io/correlation-api:${IMAGE_TAG} \
        ./corporate-app/correlation-api

        docker push \
        orstedlabacr.azurecr.io/correlation-api:${IMAGE_TAG}

    - name: Update Helm image tag
      run: |
        sed -i "s/tag: v1/tag: ${{ github.sha }}/" platform/helm/corporate-app/values.yaml

        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        git add platform/helm/corporate-app/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
