namespace: orsted-lab

correlation:
  image:
    repository: orstedlabacr.azurecr.io/correlation-api
    tag: 131660daff54348e930cb739d26f0ce903962e71

submission:
  image:
    repository: orstedlabacr.azurecr.io/submission-api
    tag: 131660daff54348e930cb739d26f0ce903962e71

replicaCount: 2

service:
  port: 80
  targetPort: 8000
