namespace: orsted-lab

correlation:
  image:
    repository: orstedlabacr.azurecr.io/correlation-api
    tag: 5248a4110cbd8a22f5b5ad3e4e476b6c066b11da

submission:
  image:
    repository: orstedlabacr.azurecr.io/submission-api
    tag: v1

replicaCount: 2

service:
  port: 80
  targetPort: 8000
